# Travis CI configuration for remote testing.
# See:
#   https://docs.travis-ci.com/user/customizing-the-build/
#   https://docs.travis-ci.com/user/languages/python

language: python

python:
  - "pypy"
  - "pypy3"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.5-dev"
    - python: "nightly"

sudo: false

install:
 - pip install 'pbr>=1.9' 'setuptools>=17.1' 'mock>=2.0'
 - pip install coverage
 - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install unittest2; fi
 # Coverage 4.0 doesn't support Python 3.2
 - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
 - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi

script:
 - coverage run --source=see.py setup.py test

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pyflakes *.py | tee >(wc -l)
 - pep8 --statistics --count *.py
